minutis-redcall/redcall

symfony/bundles/PasswordLoginBundle/DependencyInjection/PasswordLoginExtension.php
symfony/bundles/PasswordLoginBundle/EventListener/CsrfExceptionListener.php
symfony/bundles/PasswordLoginBundle/Resources/config/listeners.yml
symfony/bundles/PasswordLoginBundle/Resources/translations/messages.en.yml
symfony/bundles/PasswordLoginBundle/Resources/translations/messages.fr.yml
symfony/bundles/PasswordLoginBundle/Resources/views/error/csrf.html.twig

currently a 500 were thrown, which pollutes monitoring for nothing

handle csrf issues in a gentle way

---

symfony/src/Controller/ExportController.php
symfony/templates/export/body.html.twig
symfony/templates/export/footer.html.twig
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

Do a few changes to fit with territorial direction's needs

---

symfony/src/Repository/MessageRepository.php

currently if we clicked on another answer, the old and the new ones had the same timestamp which broken sse

sse is based on answers update time

---

symfony/src/Entity/Answer.php
symfony/src/Repository/MessageRepository.php

implemented a better way than sleep()

continuing to tackle sse issue

---

symfony/src/Command/SendMessageCommand.php
symfony/src/Communication/Formatter.php
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

if volunteer has turned off his phone for a few hours, he will need to know at what time the alert were triggered

Add date and time on smses

---

symfony/src/Command/SendCommunicationCommand.php

execprocessor will be replaced by cloud pubsub/functions soon enough

limit to 2 sms per second

---

symfony/composer.lock
symfony/config/packages/doctrine.yaml
symfony/data/fixtures.sql
symfony/src/Entity/Tag.php
symfony/src/Migrations/Version20190616024339.php
symfony/src/Services/VolunteerImporter.php
symfony/symfony.lock

A freshly created database must include the tags in order to avoid null values between volunteer and tag mapping.
And we should ignore the "session" table (non managed by Doctrine) in order to create database diffs without dropping it.

Fix tags initialization

---

docs/tech/00-development.md
symfony/composer.lock
symfony/data/fixtures.sql
symfony/src/Repository/VolunteerRepository.php

add a volunteers generator to allow developpers use the app even without pegass directory access

volunteer generator for dev env

---

symfony/composer.lock
symfony/src/Communication/Dispatcher.php
symfony/src/Controller/MessageController.php
symfony/src/Entity/Communication.php
symfony/src/Repository/MessageRepository.php
symfony/symfony.lock

Previously, multiple answers saved each word of the message in separate Message rows.
Now, the message is saved as a hole for each choice.
An even better way would be to use a ManyToMany relation between Answer and Choice

Change how multiple choices are handled

---

symfony/src/Command/PegassCommand.php
symfony/src/Entity/Pegass.php
symfony/src/Manager/PegassManager.php
symfony/src/Migrations/Version20200113222634.php
symfony/src/Repository/PegassRepository.php
symfony/src/Services/PegassClient.php

Initial import in progress
```
* * * * * ( cd /Users/alain/dev/redcall/front/symfony && sudo -u alain /usr/local/bin/php bin/console pegass 2>>/tmp/cron.err >> /tmp/cron.out )
```
```
mysql> select type, count(*) as total, sum(if(updated_at < '2000-01-01', 0, 1)) as imported from pegass group by type;
+------------+-------+----------+
| type       | total | imported |
+------------+-------+----------+
| area       |     1 |        1 |
| department |   117 |      117 |
| structure  |  1167 |       45 |
| volunteer  |  3840 |        0 |
+------------+-------+----------+
4 rows in set (0.01 sec)
```
Updates will then be split, spread over the whole resources lifetime

Pegass crawler

---

deploy/deploy.sh
deploy/migrate.sh
symfony/bundles/sandbox-bundle/Provider/FakeEmailProvider.php
symfony/config/packages/security.yaml
symfony/src/Command/SendCommunicationCommand.php
symfony/src/Communication/Sender.php
symfony/src/Controller/Admin/CampaignController.php
symfony/src/Controller/Admin/PegassController.php
symfony/src/Controller/DeployController.php
symfony/src/Controller/MessageController.php
symfony/src/Entity/Message.php
symfony/src/Manager/MessageManager.php
symfony/src/Migrations/Version20200322164033.php
symfony/src/Provider/Email/EmailProvider.php
symfony/src/Provider/Email/SymfonyEmailProvider.php
symfony/src/Repository/MessageRepository.php
symfony/src/Services/MessageFormatter.php
symfony/templates/admin/pegass/index.html.twig
symfony/templates/admin/pegass/structures.html.twig
symfony/templates/message/email.html.twig
symfony/templates/message/index.html.twig
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

Refactoring of the messages sent by email (using HTML templates)
Add a deploy lock (if a communication is being sent, deploy is canceled)

Changes of the day

---

CONTRIBUTING.md
symfony/bundles/sandbox-bundle/Controller/FixturesController.php
symfony/bundles/sandbox-bundle/Manager/FixturesManager.php
symfony/bundles/sandbox-bundle/Resources/config/controller.yaml
symfony/bundles/sandbox-bundle/Resources/config/manager.yaml
symfony/bundles/sandbox-bundle/Resources/translations/messages.en.yml
symfony/bundles/sandbox-bundle/Resources/translations/messages.fr.yml
symfony/bundles/sandbox-bundle/Resources/views/fixtures/index.html.twig
symfony/bundles/sandbox-bundle/Resources/views/home/index.html.twig
symfony/src/Manager/TagManager.php
symfony/src/Tools/Random.php
symfony/templates/admin/campaign/index.html.twig
symfony/templates/admin/campaign/table.html.twig
symfony/templates/admin/home.html.twig
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

Added some back buttons / renamed some labels to avoid confusions
Added a fixtures generator

Alain 2020 03 22 / 2

---

symfony/src/Controller/Admin/CampaignController.php
symfony/src/Controller/Admin/HomeController.php
symfony/src/Controller/Admin/PegassController.php
symfony/src/Controller/CampaignController.php
symfony/src/Controller/Management/StructuresController.php
symfony/src/Controller/Management/VolunteersController.php
symfony/src/Form/Type/CommunicationType.php
symfony/src/Manager/CampaignManager.php
symfony/src/Manager/RefreshManager.php
symfony/src/Manager/StructureManager.php
symfony/src/Manager/UserInformationManager.php
symfony/src/Repository/CampaignRepository.php
symfony/src/Repository/StructureRepository.php
symfony/src/Repository/VolunteerRepository.php
symfony/src/Security/Voter/CampaignVoter.php
symfony/src/Security/Voter/StructureVoter.php

In order to contact RedCall users, add a RedCall structure only containing them.

Redcall structure

---

symfony/bundles/twilio-bundle/Controller/StatusController.php
symfony/bundles/twilio-bundle/Entity/TwilioStatus.php
symfony/bundles/twilio-bundle/Manager/TwilioStatusManager.php
symfony/bundles/twilio-bundle/Repository/TwilioMessageRepository.php
symfony/bundles/twilio-bundle/Repository/TwilioStatusRepository.php
symfony/bundles/twilio-bundle/Resources/config/controller.yml
symfony/bundles/twilio-bundle/Resources/config/manager.yml
symfony/bundles/twilio-bundle/Resources/config/repository.yml
symfony/src/Controller/Management/VolunteersController.php
symfony/src/Entity/Communication.php
symfony/src/Entity/Message.php
symfony/src/Migrations/Version20200329205246.php
symfony/templates/admin/pegass/index.html.twig
symfony/templates/admin/pegass/structures.html.twig
symfony/templates/infos.html.twig
symfony/templates/management/home.html.twig
symfony/templates/management/volunteers/form.html.twig
symfony/templates/management/volunteers/structures.html.twig
symfony/templates/status_communication/index.html.twig
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

Several changes

---

symfony/src/Controller/Admin/PrefilledAnswersController.php
symfony/src/Controller/Management/Structure/PrefilledAnswersController.php
symfony/src/Controller/WidgetController.php
symfony/src/Entity/PrefilledAnswers.php
symfony/src/Entity/Structure.php
symfony/src/Manager/PrefilledAnswersManager.php
symfony/src/Migrations/Version20200328102824.php
symfony/src/Repository/PrefilledAnswersRepository.php
symfony/templates/management/structures/list.html.twig
symfony/templates/management/structures/prefilled_answers/editor.html.twig
symfony/templates/management/structures/prefilled_answers/list.html.twig
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

144 prefilled answers structure

---

symfony/bundles/sandbox-bundle/Controller/FixturesController.php
symfony/bundles/sandbox-bundle/Resources/views/fixtures/index.html.twig
symfony/src/Controller/Management/StructuresController.php
symfony/src/Controller/WidgetController.php
symfony/src/Form/Type/StructureType.php
symfony/src/Form/Type/StructureWidgetType.php
symfony/src/Form/Type/VolunteerWidgetType.php
symfony/src/Manager/StructureManager.php
symfony/templates/form_theme.html.twig
symfony/templates/management/structures/form.html.twig
symfony/templates/management/structures/list.html.twig
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

223 create structure

---

symfony/assets/css/main.css
symfony/assets/js/buttons-timeout.js
symfony/assets/js/main.js
symfony/src/Form/Type/VolunteerType.php
symfony/templates/admin/maintenance/index.html.twig
symfony/templates/macros.html.twig
symfony/templates/status_communication/index.html.twig
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

126 button disabled on submit

---

symfony/src/Controller/CommunicationController.php
symfony/templates/status_communication/index.html.twig
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

165 relaunch communication

---

symfony/src/Controller/Admin/MaintenanceController.php
symfony/src/Manager/MaintenanceManager.php
symfony/src/Manager/RefreshManager.php
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

these buttons are since some months for developer access only and they are supposed to know how to use it

remove protection on "pegass sync" buttons

---

symfony/src/Controller/Api/StructureController.php
symfony/src/Controller/Management/Volunteer/VolunteersController.php
symfony/src/Facade/Structure/VolunteerFiltersFacade.php
symfony/src/Manager/VolunteerManager.php
symfony/src/Repository/VolunteerRepository.php
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

Volunteers in structure: add an option to include volunteers in underlying structures

Display volunteers in underlying structures

---

symfony/src/Entity/Volunteer.php
symfony/src/Facade/Volunteer/VolunteerFiltersFacade.php

- No default minority make deleted volunteer updates crash (not nullable field)
- prod in php 7.4

[Fixes] following minority changes

---

deploy/prod/cron.yaml
symfony/config/services.yaml
symfony/src/Communication/Sender.php
symfony/src/Controller/OAuth/GoogleConnectController.php
symfony/src/Provider/OAuth/GoogleConnect/GoogleConnect.php
symfony/src/Services/InstancesNationales/VolunteerService.php
symfony/src/Task/SendCommunicationTask.php
symfony/src/Task/SyncAnnuaire.php
symfony/templates/management/volunteers/form.html.twig
symfony/translations/messages.en.yml
symfony/translations/messages.fr.yml

- Fixed the missing cron job on app engine
- Use of the long URL for authentication purposes, in order to comply with internal firewalls
- Fixed a few bugs in the "annuaire national" sync
- Use a tab system for the "volunteer edition" page

Annuaire national: a few tweaks
